apiVersion: v1
kind: Service
metadata:
  name: petapp-service
  namespace: petapp
spec:
  type: LoadBalancer
  selector:
    app: petapp
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
