name: Prometheus Setup
on: 
  workflow_call:
jobs:
  install_Prometheus:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Configure kubectl
        run: |
          aws eks --region ap-southeast-2 update-kubeconfig --name monitoring_cluster

      - name: Prometheus Helm repo add
        working-directory: prometheus
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Create namespace (if not exists)
        run: |
          kubectl create namespace prometheus || true

      - name: Install Prometheus
        working-directory: prometheus
        run: |
          helm upgrade --install prometheus prometheus-community/prometheus -f values.yml --namespace prometheus
